# =============================================
# Configuration du serveur Luanti
# =============================================

# Informations serveur
server_name = Luanti Docker MBA
server_description = Serveur Luanti dockerise avec monitoring Prometheus + Grafana
motd = Bienvenue ! Consultez la landing page sur http://localhost:8080

# Reseau
port = 30000

# Activer le endpoint /metrics pour Prometheus
# Ecoute sur toutes les interfaces (0.0.0.0) pour etre accessible
# depuis les autres conteneurs du reseau Docker
prometheus_listener_address = 0.0.0.0:30000

# Parametres serveur
default_game = minetest_game
creative_mode = true
enable_damage = false
max_users = 10

# Admin
name = Sheiethan